# ── Base de données H2 (pour tests) ────────────────────────────────────────────────
spring.datasource.url=jdbc:h2:mem:banking_db
spring.datasource.username=postgres
spring.datasource.password=Postgres@123
spring.datasource.driver-class-name=org.h2.Driver

# ── JPA / Hibernate ───────────────────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# ── H2 Console ───────────────────────────────────────────────────────────────
spring.h2.console.enabled=true

# ── Swagger / OpenAPI ─────────────────────────────────────────────────────────
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# ── Serveur ───────────────────────────────────────────────────────────────────
server.port=8081
spring.application.name=banque-api

# ── JWT ───────────────────────────────────────────────────────────────────────
jwt.secret=Y2VjaS1lc3QtdW5lLWNsZS1qd3QtdHJlcy1sb25ndWUtcG91ci1sYS1kZW1vLTEyMzQ1Njc4OTA=
jwt.expiration=86400000
